### ISSUE TITLE
Potion Effect GUI pop up

### ISSUE THREAD

**Issue by Fortist** [dmillerw/AlchemicalBling#2]
You know, when you open your gui and it shows what you're being affected by, right?
You added the "Bauble" line in the stead of the timer. Which is fine.
But this conflicts in a few ways.
WIth NEI, the character Inventory GUI is moved to the left a bit, and your potion effect stays in place, which goes over the top left slots of the inventory
While also revealing the Infinite potion effect as shown in Vanilla, so in effect I have two pop ups saying "Regeneration" and one is baubles and another is XX:XX.

An Option to disable the "Bauble" one would be nice

**Comment by JadenWong** [comment]
got a screenshot to illustrate:http://i.imgur.com/a7HZEs6.png
As said: only if you activate NEI

**Comment by massim0g** [comment]
I'm having the same problem
